/**
 * Created by C00121 on 18/01/2017.
 */
import {Injectable} from '@angular/core';


@Injectable()
export class AppConstants {


    public APP_TENANT_CODE_XX = 'XX';
    public APP_TENANT_CODE_AM = 'AM';
    public APP_TENANT_CODE_PR = 'PR';
    public APP_TENANT_CODE_PX = 'PX';
    public APP_ENVIRONMENT_TYPE_DEV = 'DEV';
    public APP_ENVIRONMENT_TYPE_TEST = 'TEST';
    public APP_ENVIRONMENT_TYPE_MAINTENANCE = 'MAINT';
    public APP_ENVIRONMENT_TYPE_PROD = 'PROD';


    //Default Service Config
    public DEFAULT_NUM_OF_RECORDS = 5; //Number of Records
    public DEFAULT_PAGINATION_LIMIT = 200; //Number of Records
    public DEFAULT_RANGE_FOR_REGION_TRACK = 1000.0; //Meters
    public DEFAULT_BULK_DATA_SYNC_INTERVAL = 24; //Hours


    //Universal Analytics Tags
    public GUEST_HOME_SCREEN  = 'GUEST HOME SCREEN';
    public LOGIN_EVENT  = 'LOGIN EVENT';
    public GEO_LOCATION_SEARCH_EVENT  = 'GEO LOCATION SEARCH EVENT';
    public FETCH_CURRENT_GEO_LOCATION_EVENT  = 'FETCH CURRENT GEO LOCATION EVENT';
    public GEO_LOCATION_SEARCH_SCREEN  = 'GEO LOCATION SEARCH SCREEN';
    public NEAR_ME_OFFER_EVENT  = 'NEAR ME OFFER EVENT';
    public NEAR_ME_STORE_EVENT  = 'NEAR ME STORE EVENT';
    public RECOMMENDED_OFFER_EVENT  = 'RECOMMENDED OFFER EVENT';
    public FEATURED_PARTNER_EVENT  = 'FEATURED PARTNER EVENT';
    public USER_HOME_SCREEN  = 'USER HOME SCREEN';
    public LOGIN_SCREEN  = 'LOGIN SCREEN';
    public LOGIN_SUCCESSFUL  = 'LOGIN SUCCESSFUL';
    public LOGIN_UNSUCCESSFUL  = 'LOGIN UNSUCCESSFUL';
    public MENU_EVENT  = 'MENU EVENT';
    public CHAT_EVENT  = 'CHAT EVENT';
    public CONTACTS_EVENT  = 'CONTACTS EVENT';
    public RATE_THE_APP_EVENT  = 'RATE THE APP EVENT';
    public APP_SETTINGS_EVENT  = 'APP SETTINGS EVENT';
    public APP_SETTINGS_SCREEN  = 'APP SETTINGS SCREEN';
    public APP_TERMS_AND_CONDITIONS_EVENT  = 'APP TERMS AND CONDITIONS EVENT';
    public APP_TERMS_AND_CONDITIONS_SCREEN  = 'APP TERMS AND CONDITIONS SCREEN';
    public MOBILE_APP_STORE_LINK_EVENT  = 'MOBILE APP STORE LINK EVENT';
    public LOGOUT_EVENT  = 'LOGOUT EVENT';
    public MY_PROFILE_EVENT  = 'MY PROFILE EVENT';
    public MY_PROFILE_SCREEN  = 'MY PROFILE SCREEN';
    public MY_TARGETS_SCREEN  = 'MY TARGETS SCREEN';
    public MY_TARGETS_EVENT  = 'MY TARGETS EVENT';
    public MY_FAVORITES_OFFER_SCREEN  = 'MY FAVORITES OFFER SCREEN';
    public MY_FAVORITES_OFFER_EVENT  = 'MY FAVORITES OFFER EVENT';
    public MY_FAVORITES_LOCATION_SCREEN  = 'MY FAVORITES LOCATION SCREEN';
    public MY_FAVORITES_LOCATION_EVENT  = 'MY FAVORITES LOCATION EVENT';
    public MY_VOUCHERS_SCREEN = 'MY_VOUCHERS_SCREEN'
    public NEAR_ME_OFFER_SCREEN  = 'NEAR ME OFFER SCREEN';
    public NEAR_ME_STORE_SCREEN  = 'NEAR ME STORE SCREEN';
    public RECOMMENDED_OFFER_SCREEN  = 'RECOMMENDED OFFER SCREEN';
    public PARTNER_LOCATION_DETAIL_SCREEN  = 'PARTNER LOCATION DETAIL SCREEN';
    public PARTNER_LOCATION_CARD  = 'PARTNER LOCATION CARD';
    public OFFER_CARD  = 'OFFER CARD';
    public TERGET_CARD  = 'TARGET CARD';
    public PARTNER_DETAIL_SCREEN  = 'PARTNER DETAIL SCREEN';
    public LIKE_OFFER_EVENT  = 'LIKE OFFER EVENT';
    public UNLIKE_OFFER_EVENT  = 'UNLIKE OFFER EVENT';
    public TARGET_OFFER_EVENT  = 'TARGET OFFER EVENT';
    public LOCATION_OFFER_EVENT  = 'LOCATION OFFER EVENT';
    public LIKE_LOCATION_EVENT  = 'LIKE LOCATION EVENT';
    public UNLIKE_LOCATION_EVENT  = 'UNLIKE LOCATION EVENT';
    public LIKE_PARTNER_EVENT  = 'LIKE PARTNER EVENT';
    public UNLIKE_PARTNER_EVENT  = 'UNLIKE PARTNER EVENT';
    public CHECKIN_LOCATION_EVENT  = 'CHECKIN LOCATION EVENT';
    public VIRTUAL_CARD_SCREEN  = 'VIRTUAL CARD SCREEN';
    public QR_CODE_EVENT  = 'QR CODE EVENT';
    public QR_CODE_SCREEN  = 'QR CODE SCREEN';
    public FULL_SCREEN_EVENT  = 'FULL SCREEN EVENT';
    public FULL_SCREEN_SCREEN  = 'FULL SCREEN SCREEN';
    public FLIP_EVENT  = 'FLIP EVENT';
    public SEARCH_PARTNER_SCREEN  = 'SEARCH PARTNER SCREEN';
    public INDUSTRY_TYPE_FILTER_EVENT  = 'INDUSTRY TYPE FILTER EVENT';
    public SEARCH_PARTNER_KEY_EVENT  = 'SEARCH PARTNER KEY EVENT';
    public SEARCH_OFFER_SCREEN  = 'SEARCH OFFER SCREEN';
    public SEARCH_EARN_OFFER_FILTER_EVENT  = 'SEARCH EARN OFFER FILTER EVENT';
    public SEARCH_BURN_OFFER_FILTER_EVENT  = 'SEARCH BURN OFFER FILTER EVENT';
    public SEARCH_OFFER_KEY_EVENT  = 'SEARCH OFFER KEY EVENT';
    public SEARCH_LOCATION_SCREEN  = 'SEARCH LOCATION SCREEN';
    public SEARCH_LOCATION_KEY_EVENT  = 'SEARCH LOCATION KEY EVENT';
    public SEARCH_VOUCHER_SCREEN  = 'SEARCH VOUCHER SCREEN';
    public SEARCH_VOUCHER_KEY_EVENT  = 'SEARCH VOUCHER KEY EVENT';
    public FACEBOOK_LOGIN_EVENT  = 'FACEBOOK LOGIN EVENT';
    public APP_SETTINGS_NOTIFICATION_EVENT  = 'APP SETTINGS NOTIFICATION EVENT';
    public APP_SETTINGS_LANGUAGE_EVENT  = 'APP SETTINGS LANGUAGE EVENT';
    public CREATE_PERSONAL_TARGET_EVENT  = 'CREATE PERSONAL TARGET EVENT';
    public VIEW_ALL_TARGETS_EVENT  = 'VIEW ALL TARGETS EVENT';
    public VIEW_ALL_VOUCHERS_EVENT  = 'VIEW ALL VOUCHERS EVENT';
    public DROP_TARGETS_EVENT  = 'DROP TARGETS EVENT';
    public SHARE_TARGET_EVENT  = 'SHARE TARGET EVENT';
    public VIEW_ALL_TARGETS_SCREEN  = 'VIEW ALL TARGETS SCREEN';
    public VIEW_ALL_VOUCHERS  = 'VIEW ALL VOUCHERS SCREEN';
    public CREATE_PERSONAL_TARGET_SCREEN  = 'CREATE PERSONAL TARGET SCREEN';
    public APP_MENU_SCREEN  = 'APP MENU SCREEN';
    public USER_ENROLLMENT_EVENT  = 'USER ENROLLMENT EVENT';
    public OFFER_LOCATION_EVENT  = 'OFFER LOCATION EVENT';
    public PARTNER_LOCATION_EVENT  = 'PARTNER LOCATION EVENT';
    public MORE_INFO_EVENT  = 'MORE INFO EVENT';
    public FORGOT_PASSWORD_EVENT  = 'FORGOT PASSWORD EVENT';
    public REGISTER_NOW_EVENT  = 'REGISTER NOW EVENT';
    public PARTNER_TERMS_EVENT  = 'PARTNER TERMS EVENT';
    public ENROLLMENT_SCREEN  = 'USER ENROLLMENT SCREEN';
    public EDIT_PROFILE_SCREEN  = 'EDIT PROFILE SCREEN';
    public ENROLLMENT_EXIT_EVENT  = 'USER ENROLLMENT EXIT EVENT';
    public EDIT_PROFILE_EXIT_EVENT  = 'EDIT PROFILE EXIT EVENT';
    public ENROLLMENT_EDIT_AGAIN_EVENT  = 'USER ENROLLMENT EDIT AGAIN EVENT';
    public EDIT_PROFILE_EDIT_AGAIN_EVENT  = 'EDIT PROFILE EDIT AGAIN EVENT';
    public TERMS_CONDITIONS_TAPPED_EVENT  = 'TERMS AND CONDITIONS TAPPED EVENT';
    public PRIVACY_POLICY_TAPPED_EVENT  = 'PRIVACY POLICY TAPPED EVENT';
    public SHOW_HIDE_PASSWORD_TEXT_TAPPED_EVENT  = 'SHOW HIDE PASSWORD TEXT TAPPED EVENT';
    public SHOW_HIDE_ANSWER_TEXT_TAPPED_EVENT  = 'SHOW HIDE ANSWER TEXT TAPPED EVENT';
    public INVALID_PASSWORD_EVENT  = 'INVALID PASSWORD EVENT';
    public SUBMIT_SAVE_EVENT  = 'SUBMIT SAVE EVENT';
    public ENROLLMENT_SUCCESSFUL_EVENT  = 'USER ENROLLMENT SUCCESSFUL EVENT';
    public ENROLLMENT_UNSUCCESSFUL_EVENT  = 'USER ENROLLMENT UNSUCCESSFUL EVENT';
    public EDIT_PROFILE_SUCCESSFUL_EVENT  = 'EDIT PROFILE SUCCESSFUL EVENT';
    public EDIT_PROFILE_UNSUCCESSFUL_EVENT  = 'EDIT PROFILE UNSUCCESSFUL EVENT';
    public ENROLLMENT_SUCCESSFUL_WELCOME_SCREEN  = 'USER ENROLLMENT SUCCESSFUL WELCOME SCREEN';
    public EDIT_PASSWORD_SUCCESSFUL_EVENT  = 'EDIT PASSWORD SUCCESSFUL EVENT';
    public EDIT_PASSWORD_UNSUCCESSFUL_EVENT  = 'EDIT PASSWORD UNSUCCESSFUL EVENT';
    public SECURITY_QUESTION_UPDATE_SUCCESSFUL_EVENT  = 'SECURITY QUESTION UPDATE SUCCESSFUL EVENT';
    public SECURITY_QUESTION_UPDATE_UNSUCCESSFUL_EVENT  = 'SECURITY QUESTION UPDATE UNSUCCESSFUL EVENT';

    //Headings and Page Titles
    public HEADING_NEAR_ME_OFFERS = 'NEAR_ME_OFFERS';
    public HEADING_NEAR_ME_STORES = 'NEAR_ME_STORES';
    public HEADING_RECOMMENDED_OFFERS = 'RECOMMENDED_OFFERS';
    public HEADING_MY_TARGETS = 'MY_GOALS';
    public HEADING_MY_FAVOURITE_OFFERS = 'MY_FAVOURITE_OFFERS';
    public HEADING_MY_FAVOURITE_LOCATIONS = 'MY_FAVOURITE_LOCATIONS';


    //Event Constants
    public EVENT_CONFIG_DATA_CHANGED = 'CONFIG_DATA_CHANGED';
    public EVENT_LOGIN_STATUS_CHANGED = 'LOGIN_STATUS_CHANGED';
    public EVENT_USER_PROFILE_CHANGED = 'USER_PROFILE_CHANGED';
    public EVENT_MENU_INFO_CHANGED = 'MENU_INFO_CHANGED';
    public EVENT_APP_TERMS_CHANGED = 'APP_TERMS_CHANGED';
    public EVENT_WALLET_INFO_CHANGED = 'WALLET_INFO_CHANGED';
    public EVENT_RECOMMENDED_OFFERS_CHANGED = 'RECOMMENDED_OFFERS_CHANGED';
    public EVENT_FAVORITE_OFFERS_CHANGED = 'FAVORITE_OFFERS_CHANGED';
    public EVENT_NEARBY_OFFERS_CHANGED = 'NEARBY_OFFERS_CHANGED';
    public EVENT_FEATURED_PARTNERS_CHANGED = 'FEATURED_PARTNERS_CHANGED';
    public EVENT_FAVORITE_PARTNER_LOCATIONS_CHANGED = 'FAVORITE_PARTNER_LOCATIONS_CHANGED';
    public EVENT_NEARBY_PARTNER_LOCATIONS_CHANGED = 'NEARBY_PARTNER_LOCATIONS_CHANGED';
    public EVENT_VOUCHER_CHANGED = 'VOUCHER_CHANGED';
    public EVENT_TARGET_CHANGED = 'TARGET_CHANGED';
    public EVENT_RECENT_TRANSACTIONS_CHANGED = 'RECENT_TRANSACTIONS_CHANGED';
    public EVENT_LOCATION_NOTIFICATION_CHANGED = 'LOCATION_NOTIFICATION_CHANGED';
    public EVENT_USER_LOCATION_CHANGED = 'USER_LOCATION_CHANGED';
    public EVENT_NETWORK_STATUS_CONNECTED = 'NETWORK_STATUS_CONNECTED';
    public EVENT_NETWORK_STATUS_DISCONNECTED = 'NETWORK_STATUS_DISCONNECTED';
    public EVENT_APP_LANGUAGE_CHANGED = 'APP_LANGUAGE_CHANGED';
    public EVENT_APP_DATA_SYNC_REQUEST = 'APP_DATA_SYNC_REQUEST';
    public EVENT_USER_SESSION_EXPIRED = 'USER_SESSION_EXPIRED';
    public EVENT_OPEN_ENROLLMENT_PAGE = 'OPEN_ENROLLMENT_PAGE';
    public EVENT_APP_RESUMES = 'APP_RESUMES';


    //Wallet Image File
    public WALLET_CARD_FRONT_IMAGE = 'virtual_card_front.jpg';
    public WALLET_CARD_BACK_IMAGE = 'virtual_card_back.jpg';
    public WALLET_CARD_FRONT_MASTER_IMAGE_NAME = '-MASTER';
    public WALLET_QR_CODE_IMAGE = 'wallet_qr_code.jpg';


    //Chat File Name
    public CHAT_FILE_NAME = 'Chat.html';


    constructor(){

    }

}
